//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdk_test.TestResources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sdk_test.TestResources.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 00c1a1018effde47c68134995a237bc05cc703c3fee22ac721175547f542951e97785c92a7c330dff8aab6a2374cf1858af9a7cf5a8732000c52d6ae73597e5b702fafce43480b21811d8e7a90b300ff758df5b0c6337da14dc9c4959fd937c5f9d2ca1b19199e2f89018e06443a0cf347ea0d7f486c6dea46b037d748c7cc7703e686cdf4314b17ca263d5aba273905c5925a043c09e542425a33e0850d284584d3c1760ec1d9ad03e32f7e6593e7ec123306e87e252281d7a799cab516138f76212c31d0888b0345d1726ae49b17b19d48b80ed0af48cff0ff7eadf12a60d4cb4df3789363da9fc2a6635fe1152ba4e32e6b05fb972e8ae6e8b6c733582eb2 [stringa troncata]&quot;;.
        /// </summary>
        internal static string EncodedHexPubModulus {
            get {
                return ResourceManager.GetString("EncodedHexPubModulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 65537.
        /// </summary>
        internal static string PubExponentTextValue {
            get {
                return ResourceManager.GetString("PubExponentTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a -----BEGIN PUBLIC KEY-----
        ///MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwaEBjv/eR8aBNJlaI3vA
        ///XMcDw/7iKschF1VH9UKVHpd4XJKnwzDf+Kq2ojdM8YWK+afPWocyAAxS1q5zWX5b
        ///cC+vzkNICyGBHY56kLMA/3WN9bDGM32hTcnElZ/ZN8X50sobGRmeL4kBjgZEOgzz
        ///R+oNf0hsbepGsDfXSMfMdwPmhs30MUsXyiY9WronOQXFkloEPAnlQkJaM+CFDShF
        ///hNPBdg7B2a0D4y9+ZZPn7BIzBuh+JSKB16eZyrUWE492ISwx0IiLA0XRcmrkmxex
        ///nUi4DtCvSM/w/36t8Spg1MtN83iTY9qfwqZjX+EVK6TjLmsF+5cuiubotsczWC6y
        ///rQIDAQAB
        ///-----END PUBLIC KEY-----.
        /// </summary>
        internal static string RSAPublicText {
            get {
                return ResourceManager.GetString("RSAPublicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///  &quot;height&quot;: &quot;0&quot;,
        ///  &quot;result&quot;: [
        ///    {
        ///      &quot;sender&quot;: &quot;did:com:1zfhgwfgex8rc9t00pk6jm6xj6vx5cjr4ngy32v&quot;,
        ///      &quot;recipient&quot;: &quot;did:com:1g5cxz9p7dqux80sw5tljwg2pwz6x7zlq84km56&quot;,
        ///      &quot;uuid&quot;: &quot;6a881ef0-04da-4524-b7ca-6e5e3b7e61dc&quot;,
        ///      &quot;metadata&quot;: {
        ///        &quot;content_uri&quot;: &quot;https://www.vargroup.it/managed-security-services/&quot;,
        ///        &quot;schema_type&quot;: &quot;&quot;,
        ///        &quot;schema&quot;: {
        ///          &quot;uri&quot;: &quot;https://www.vargroup.it/managed-security-services/metadata/schema&quot;,
        ///          &quot;version&quot;: &quot;1.0.0&quot;
        ///        }, [stringa troncata]&quot;;.
        /// </summary>
        internal static string SentDocumentResponseJson {
            get {
                return ResourceManager.GetString("SentDocumentResponseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///  &quot;height&quot;: &quot;0&quot;,
        ///  &quot;result&quot;: {
        ///    &quot;tumbler_address&quot;: &quot;did:com:14ttg3eyu88jda8udvxpwjl2pwxemh72w0grsau&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string tumblerAddressJson {
            get {
                return ResourceManager.GetString("tumblerAddressJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///  &quot;height&quot;: &quot;0&quot;,
        ///  &quot;result&quot;: {
        ///    &quot;owner&quot;: &quot;did:com:14ttg3eyu88jda8udvxpwjl2pwxemh72w0grsau&quot;,
        ///    &quot;did_document&quot;: {
        ///      &quot;@context&quot;: &quot;https://www.w3.org/ns/did/v1&quot;,
        ///      &quot;id&quot;: &quot;did:com:14ttg3eyu88jda8udvxpwjl2pwxemh72w0grsau&quot;,
        ///      &quot;publicKey&quot;: [
        ///        {
        ///          &quot;id&quot;: &quot;did:com:14ttg3eyu88jda8udvxpwjl2pwxemh72w0grsau#keys-1&quot;,
        ///          &quot;type&quot;: &quot;RsaVerificationKey2018&quot;,
        ///          &quot;controller&quot;: &quot;did:com:14ttg3eyu88jda8udvxpwjl2pwxemh72w0grsau&quot;,
        ///          &quot;publicKeyPem&quot;: &quot;-----BEGIN PUBLIC [stringa troncata]&quot;;.
        /// </summary>
        internal static string tumblerIdentityJson {
            get {
                return ResourceManager.GetString("tumblerIdentityJson", resourceCulture);
            }
        }
    }
}
